"""Export endpoints for PDF, documents, etc."""
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from datetime import datetime

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.transcript import Transcript
from app.models.encounter import Encounter
from app.services.soap_service import soap_service

router = APIRouter()


class ExportRequest(BaseModel):
    """Export request schema."""
    encounter_id: int
    template: str = "soap"  # soap, letter, full


@router.post("/pdf")
async def export_pdf(
    export_req: ExportRequest,
    current_user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Export encounter transcript as PDF."""
    # Get encounter
    result = await db.execute(
        select(Encounter).where(Encounter.id == export_req.encounter_id)
    )
    encounter = result.scalar_one_or_none()

    if not encounter:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Encounter not found",
        )

    # Get transcript
    result = await db.execute(
        select(Transcript)
        .where(Transcript.encounter_id == export_req.encounter_id)
        .order_by(Transcript.created_at.desc())
    )
    transcript = result.scalar_one_or_none()

    if not transcript:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Transcript not found",
        )

    # Generate PDF
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title = Paragraph(
        f"<b>Medical Consultation Transcript</b>",
        styles['Title']
    )
    story.append(title)
    story.append(Spacer(1, 12))

    # Metadata
    metadata = f"""
    <b>Date:</b> {encounter.started_at.strftime('%Y-%m-%d %H:%M')}<br/>
    <b>Patient Reference:</b> {encounter.patient_ref or 'N/A'}<br/>
    <b>Doctor ID:</b> {encounter.doctor_id}<br/>
    <b>Status:</b> {encounter.status.value}<br/>
    """
    story.append(Paragraph(metadata, styles['Normal']))
    story.append(Spacer(1, 20))

    # SOAP Notes if available
    if transcript.soap_notes:
        soap = transcript.soap_notes
        story.append(Paragraph("<b>SOAP NOTES</b>", styles['Heading1']))
        story.append(Spacer(1, 12))

        for section in ['S', 'O', 'A', 'P']:
            if section in soap:
                content = soap[section].replace('\n', '<br/>')
                story.append(Paragraph(content, styles['Normal']))
                story.append(Spacer(1, 12))

    # Full transcript
    story.append(Spacer(1, 20))
    story.append(Paragraph("<b>FULL TRANSCRIPT</b>", styles['Heading1']))
    story.append(Spacer(1, 12))

    # Format transcript text
    transcript_text = transcript.text.replace('\n', '<br/>')
    story.append(Paragraph(transcript_text, styles['Normal']))

    # Footer
    story.append(Spacer(1, 30))
    footer_text = f"""
    <i>This document was generated by AIscribe on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}.</i><br/>
    <i>This is a computer-generated draft. Please review and sign off before finalizing.</i>
    """
    story.append(Paragraph(footer_text, styles['Normal']))

    # Build PDF
    doc.build(story)

    # Return PDF as download
    buffer.seek(0)
    filename = f"transcript_{encounter.id}_{datetime.utcnow().strftime('%Y%m%d')}.pdf"

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )


@router.post("/text")
async def export_text(
    export_req: ExportRequest,
    current_user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Export encounter transcript as plain text."""
    # Get transcript
    result = await db.execute(
        select(Transcript)
        .where(Transcript.encounter_id == export_req.encounter_id)
        .order_by(Transcript.created_at.desc())
    )
    transcript = result.scalar_one_or_none()

    if not transcript:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Transcript not found",
        )

    # Format as text
    output = f"MEDICAL CONSULTATION TRANSCRIPT\n"
    output += f"=" * 50 + "\n\n"

    if transcript.soap_notes:
        output += "SOAP NOTES\n\n"
        for section, content in transcript.soap_notes.items():
            output += f"{content}\n\n"

    output += f"FULL TRANSCRIPT\n\n{transcript.text}\n"

    # Return as downloadable text file
    filename = f"transcript_{export_req.encounter_id}.txt"

    return StreamingResponse(
        iter([output]),
        media_type="text/plain",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )
